import { create } from 'zustand';

type Language = 'en' | 'hi';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar
    'nav.dashboard': 'Dashboard',
    'nav.crop': 'Crop Analysis',
    'nav.weather': 'Weather',
    'nav.irrigation': 'Irrigation',
    'nav.marketplace': 'Marketplace',
    'nav.sell': 'Sell crops',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.getStarted': 'Get Started',
    'nav.signOut': 'Sign Out',
    'nav.switchLanguage': 'Switch to Hindi',
    'nav.appName': 'Kisan Sathi',
    
    // Generic
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error Occurred',
    'common.missingApiKey': 'Missing Weather API Key',
    'common.apiKeySetup': 'Please enter a valid OpenWeather API key in the settings panel to enable weather intelligence.',
    'common.organic': 'Organic',
    'common.sustainable': 'Sustainable',
    'common.searchSector': 'Search Sector...',
    'common.lastSync': 'Last Sync',
    'common.actionRequired': 'ACTION REQUIRED',
    'common.priority': 'Priority',
    'common.low': 'Low',
    'common.medium': 'Medium',
    'common.high': 'High',
    'common.farmer': 'Farmer',
    'common.consumer': 'Consumer',
    'common.analyst': 'Analyst',
    'common.admin': 'Admin',
    
    // Weather
    'weather.title': 'Weather Intelligence',
    'weather.search': 'Search city...',
    'weather.lastUpdated': 'Last Updated',
    'weather.feelsLike': 'Feels like',
    'weather.humidity': 'Humidity',
    'weather.wind': 'Wind Speed',
    'weather.visibility': 'Visibility',
    'weather.forecast': 'Extended Forecast',
    'weather.advisory': 'Heat Stress Advisory',
    'weather.opportunity': 'Irrigation Opportunity',
    
    // Dashboard
    'dash.title': 'Environmental Intel',
    'dash.systemsOptimal': 'Systems Optimal',
    'dash.refresh': 'Refresh Data',
    'dash.temp': 'Temperature',
    'dash.airQuality': 'Air Quality',
    'dash.precip': 'Precipitation',
    'dash.risk': 'Crop Risk Score',
    'dash.alerts': 'System Alerts',
    'dash.tasks': 'Upcoming Tasks',
    'dash.noTasks': 'No Tasks Queued',
    'dash.awaitingDirectives': 'Awaiting new directives.',
    'dash.submitTask': 'Submit Task',
    'dash.missionObjective': 'Mission Objective...',
    'dash.planetaryResourceFlow': 'Planetary Resource Flow',
    'dash.multispectralTelemetry': 'Multispectral telemetry stream',
    'dash.solarIrradiance': 'Solar irradiance nominal',
    'dash.soilEvap': 'Soil evaporation active',
    'dash.telemetryMissing': 'Telemetry missing',
    'dash.locating': 'Locating System...',

    // Landing
    'landing.aiTag': 'AI-Powered Agriculture',
    'landing.heroTitle1': 'Protecting',
    'landing.heroTitle2': 'Crops',
    'landing.heroTitle3': 'Lives',
    'landing.heroDesc': 'Kisan Sathi leverages cutting-edge environmental intelligence and smart farming tools to build a sustainable future for our planet\'s food systems.',
    'landing.btnAnalyze': 'Analyze Crop',
    'landing.btnMonitor': 'Monitor Environment',
    'landing.stats1Label': 'Crops Protected',
    'landing.stats2Label': 'Water Saved',
    'landing.stats3Label': 'Risk Accuracy',
    'landing.stats4Label': 'Farmers Impacted',
    'landing.launchModule': 'Launch Module',
    'landing.futureTitle': 'The Future of Farming',
    'landing.futureDesc': 'Intelligent tools designed for modern environmental challenges.',
    'landing.feature1Title': 'Disease Detection AI',
    'landing.feature1Desc': 'Upload crop photos and get instant diagnosis with high precision confidence scoring.',
    'landing.feature2Title': 'Real-time Monitoring',
    'landing.feature2Desc': 'Live environmental alerts for flood zones, temperature spikes, and AQI monitoring.',
    'landing.feature3Title': 'Smart Irrigation',
    'landing.feature3Desc': 'Optimize water usage with AI-driven recommendations based on soil and weather data.',
    'landing.feature4Title': 'Direct Marketplace',
    'landing.feature4Desc': 'Connect local farmers with consumers bypassing intermediaries for fair trade.',
    'landing.feature5Title': 'Disaster Alerts',
    'landing.feature5Desc': 'Stay 72 hours ahead with predictive modeling for heatwaves, storms, and pests.',
    'landing.ctaTitle': 'Ready to secure your crops?',
    'landing.ctaDesc': 'Join 850,000+ farmers and researchers building a more resilient world.',
    'landing.launchBtn': 'Launch Kisan Sathi',

    // Alerts
    'alert.heatwave': 'Heatwave Alert',
    'alert.heatwaveMsg': 'Extreme solar influx detected. Execute irrigation protocol Delta.',
    'alert.winds': 'High Velocity Winds',
    'alert.windsMsg': 'Wind velocity exceeding station stability thresholds.',
    'alert.extremeHeat': 'Extreme Heat Sync',
    'alert.extremeHeatMsg': 'Thermal runaway detected. Engaging emergency irrigation.',
    'alert.frost': 'Frost Impending',
    'alert.frostMsg': 'Low thermal energy. Activate protective canopies.',
    'alert.pathogen': 'Pathogen Risk',
    'alert.pathogenMsg': 'Hyper-moisture detected. Fungal risk elevated.',
    'alert.atmosphericCrisis': 'Atmospheric Crisis',
    'alert.atmosphericCrisisMsg': 'Dangerous aerosol levels. Seal sensitive grow sites.',
    'alert.systemNominal': 'System Nominal',
    'alert.systemNominalMsg': 'Station Alpha synced with orbital satellites.',

    // Marketplace
    'market.title': 'Market Place',
    'market.tag': 'Networked Supply',
    'market.desc': 'Commercial hub for agricultural inputs and outputs. Acquire seeds, fertilizers, and hardware directly from the network.',
    'market.startListing': 'Start Listing',
    'market.stats1Label': 'Global Commodity Index',
    'market.stats2Label': 'Verified Farmers',
    'market.stats3Label': 'Transaction Volume',
    'market.searchPlaceholder': 'Search resources...',
    'market.initiateTrade': 'Initiate Trade',
    'market.cat.All': 'All',
    'market.cat.Crop': 'Crops',
    'market.cat.Seed': 'Seeds',
    'market.cat.Fertilizer': 'Fertilizers',
    'market.cat.Tool': 'Tools',
    'market.notFound': 'Resources Not Found',
    'market.broadcasting': 'Broadcasting scan for available nodes...',
    'market.buyNow': 'Buy Now',
    'market.processing': 'Processing Trade...',

    // Sell
    'sell.tag': 'Seller Console',
    'sell.title': 'Harvest Inventory',
    'sell.desc': 'Manage your agricultural outputs and industrial supplies. Update stock levels in real-time.',
    'sell.newListing': 'New Listing',
    'sell.cancelEntry': 'Cancel Entry',
    'sell.category': 'Category',
    'sell.price': 'Price',
    'sell.unit': 'Unit',
    'sell.stock': 'Stock Available',
    'sell.missionParams': 'Mission Parameters',
    'sell.deploy': 'Deploy Listing',
    'sell.activeListings': 'Active Listings',
    'sell.decommission': 'Decommission Listing',
    'sell.zeroInventory': 'Zero Inventory Detected',
    'sell.initFirst': 'Initialize your first listing to begin operations.',
    'sell.accessRestricted': 'Access Restricted',
    'sell.identify': 'Please identify yourself to access the inventory console.',
    // Irrigation
    'irr.title': 'Hydro Genesis',
    'irr.tag': 'Resource Optimization Matrix',
    'irr.desc': 'Neural architecture for planetary scale hydration. Real-time atmospheric analysis synchronized with sub-surface soil telemetry.',
    'irr.btnCompute': 'Initialize Compute',
    'irr.syncing': 'Synchronizing',
    'irr.searchLabel': 'Search Crop Colony',
    'irr.searchPlaceholder': 'Search any crop...',
    'irr.telemetryTitle': 'Sector Telemetry',
    'irr.soilMoisture': 'Soil Moisture',
    'irr.thermals': 'Thermals (Soil/Air)',
    'irr.cloudDensity': 'Cloud Density',
    'irr.windVelocity': 'Wind Velocity',
    'irr.optimal': 'Optimal',
    'irr.manualOverride': 'Manual Override',
    'irr.standbyTitle': 'Neural Matrix Standby',
    'irr.standbyDesc': 'Select a biological colony from the telemetry stream to initialize irrigation vector calculations.',
    'irr.sustainability': 'Sustainability Index',
    'irr.resourceEff': 'Resource Efficiency',
    'irr.globalYield': 'Global Yield Impact',
    'irr.soilVitality': 'Soil Vitality',
    'irr.inputValue': 'Input Value',
    'irr.actionProtocol': 'Action Protocol Validated',
    'irr.litersPerPlant': 'LITERS / PLANT',
    'irr.temporalWindow': 'Temporal Window',
    'irr.solarSync': 'Optimized for solar shadow synchronization.',
    'irr.cyclePulsation': 'Cycle Pulsation',
    'irr.transpirationBuffering': 'Dynamic transpiration buffering active.',
    'irr.consultingAI': 'Consulting AI...',
    'irr.bioDatabase': 'Search Global Bio-Database:',

    // Crop Analysis
    'crop.title': 'Crop Diagnosis AI',
    'crop.desc': 'Upload a photo of your crop to detect diseases and get instant treatment recommendations.',
    'crop.dropText': 'Drop to upload',
    'crop.dragText': 'Drag and drop photo here',
    'crop.uploadGuidelines': 'Works for corn, wheat, rice, tomatoes, and more. JPEG/PNG up to 10MB.',
    'crop.selectImage': 'Select Image',
    'crop.instantPhoto': 'Instant Photo',
    'crop.scanningNeural': 'Scanning Neural Network...',
    'crop.analyzeHealth': 'Analyze Health',
    'crop.diagnosisComplete': 'Diagnosis Complete',
    'crop.confidenceScore': 'Confidence Score',
    'crop.risk': 'Risk',
    'crop.treatmentProtocol': 'Treatment Protocol',
    'crop.immediateAction': 'Immediate Action',
    'crop.longTermPrevention': 'Long-term Prevention',
    'crop.orderKit': 'Order Recovery Kit',
    'crop.standbyTitle': 'Neural Engine Standby',
    'crop.standbyDesc': 'Your analysis results will appear here after scanning. Our AI handles over 40+ species of crops.',
    'crop.replacePhoto': 'Replace Photo',

    // Footer
    'footer.tagline': 'Next-generation environmental intelligence platform leveraging AI to protect global food stability and rural communities.',
    'footer.platform': 'Platform',
    'footer.resources': 'Resources',
    'footer.trust': 'Trust',
    'footer.dashboard': 'Analytics Dashboard',
    'footer.cropAI': 'Crop Diagnosis AI',
    'footer.weather': 'Weather Intelligence',
    'footer.handbook': 'Farmer\'s Handbook',
    'footer.apiDoc': 'API Documentation',
    'footer.reports': 'Sustainability Reports',
    'footer.forum': 'Community Forum',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.security': 'Security Center',
    'footer.cookie': 'Cookie Policy',
    'footer.rights': 'All rights reserved.',
    'footer.madeWith': 'Made with',

    // Admin
    'admin.desc': 'System administration and planetary oversight.',
    'admin.genReport': 'Generate System Report',
    'admin.ebs': 'Emergency Broadcast System',
    'admin.ebsDesc': 'Send real-time alerts to all active personnel dashboards.',
    'admin.alertType': 'Alert Type',
    'admin.headline': 'Headline',
    'admin.msgDetails': 'Message Details',
    'admin.commence': 'Commence System-Wide Broadcast',
    'admin.userRegistry': 'User Registry',
    'admin.cropReports': 'Crop Reports',
    'admin.filterRecords': 'Filter records...',
    'admin.allRegions': 'All Regions',
    'admin.entity': 'Entity',
    'admin.status': 'Status',
    'admin.type': 'Type',
    'admin.actions': 'Actions',
    'admin.active': 'Active',
    'admin.cpuLoad': 'CPU Load',
    'admin.storage': 'Storage',
    'admin.activeSessions': 'Active Sessions',
    'admin.alertRate': 'Alert Rate',

    // Profile
    'profile.title': 'Profile Settings',
    'profile.desc': 'Update your account information and platform preferences.',
    'profile.displayName': 'Display Name',
    'profile.yourName': 'Your Name',
    'profile.platformRole': 'Platform Role',
    'profile.roleHint': 'Roles determine your access to specific modules like Marketplace (Farmer) or GIS (Analyst).',
    'profile.saveProfile': 'Save Profile',
    'profile.saving': 'Saving Changes...',
    'profile.signOut': 'Sign Out',
    'profile.accountID': 'Account ID',
    'profile.joined': 'Joined',
    'profile.back': 'Back',
    'profile.unnamed': 'Unnamed User',
    'profile.account': 'Account',

    // Auth labels
    'auth.tag': 'AI-Powered Planetary Defense System',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.loginDesc': 'Access your dashboard and reports.',
    'auth.registerDesc': 'Start your sustainability journey today.',
    'auth.iamFarmer': 'I am a Farmer',
    'auth.iamConsumer': 'I am a Consumer',
    'auth.iamAnalyst': 'I am an Analyst',
    'auth.googleAuth': 'Continue with Google',

    // Chat
    'chat.welcome': 'Hello! I am AgroAI, your planetary environmental consultant. How can I assist your farm today?',
    'chat.placeholder': 'Ask anything...',
    'chat.restore': 'Restore Intelligence Session',
    'chat.neuralLive': 'Neural Live',
    'chat.error': 'An error occurred while connecting to the neural engine.',
    'chat.noProcess': "I'm sorry, I couldn't process that request.",

    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.join': 'Join Kisan Sathi',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.signIn': 'Sign In',
    'auth.createAccount': 'Create Account',
    'auth.or': 'Or continue with',

    // Admin
    'admin.title': 'Command Core',
    'admin.users': 'System Users',
    'admin.alerts': 'Global Alerts',
    'admin.placeholder': 'Enter alert message...',
    
    // Feedback
    'feedback.title': 'Support & Feedback',
    'feedback.btn': 'Feedback',
    'feedback.category': 'Category',
    'feedback.msg': 'Your Message',
    'feedback.placeholder': 'Describe your issue or suggest a feature...',
    'feedback.submit': 'Send Feedback',
    'feedback.success': 'Thank you! Your feedback has been recorded.',
    'feedback.cat.bug': 'Bug Report',
    'feedback.cat.feature': 'Feature Request',
    'feedback.cat.general': 'General Feedback',
  },
  hi: {
    // Navbar
    'nav.dashboard': 'डैशबोर्ड',
    'nav.crop': 'फसल विश्लेषण',
    'nav.weather': 'मौसम',
    'nav.irrigation': 'सिंचाई',
    'nav.marketplace': 'मार्केटपलेस',
    'nav.sell': 'फसलें बेचें',
    'nav.admin': 'प्रशासक',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.getStarted': 'शुरू करें',
    'nav.signOut': 'साइन आउट',
    'nav.switchLanguage': 'English में बदलें',
    'nav.appName': 'किसान साथी',

    // Generic
    'common.search': 'खोजें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि हुई',
    'common.missingApiKey': 'मौसम एपीआई कुंजी गायब है',
    'common.apiKeySetup': 'मौसम जानकारी सक्षम करने के लिए कृपया सेटिंग्स पैनल में एक वैध ओपनवेदर एपीआई कुंजी दर्ज करें।',
    'common.organic': 'जैविक',
    'common.sustainable': 'सतत',
    'common.searchSector': 'क्षेत्र खोजें...',
    'common.lastSync': 'अंतिम सिंक',
    'common.actionRequired': 'कार्यवाही आवश्यक',
    'common.priority': 'प्राथमिकता',
    'common.low': 'कम',
    'common.medium': 'मध्यम',
    'common.high': 'उच्च',
    'common.farmer': 'किसान',
    'common.consumer': 'उपभोक्ता',
    'common.analyst': 'विश्लेषक',
    'common.admin': 'प्रशासक',
    
    // Weather
    'weather.title': 'मौसम जानकारी',
    'weather.search': 'शहर खोजें...',
    'weather.lastUpdated': 'पिछली बार अपडेट किया गया',
    'weather.feelsLike': 'जैसा महसूस होता है',
    'weather.humidity': 'नमी',
    'weather.wind': 'हवा की गति',
    'weather.visibility': 'दृश्यता',
    'weather.forecast': 'पूर्वानुमान',
    'weather.advisory': 'गर्मी के तनाव की सलाह',
    'weather.opportunity': 'सिंचाई का अवसर',
    
    // Dashboard
    'dash.title': 'पर्यावरण इंटेलिजेंस',
    'dash.systemsOptimal': 'सिस्टम ठीक है',
    'dash.refresh': 'डेटा रीफ्रेश करें',
    'dash.temp': 'तापमान',
    'dash.airQuality': 'वायु गुणवत्ता',
    'dash.precip': 'वर्षा',
    'dash.risk': 'फसल जोखिम स्कोर',
    'dash.alerts': 'सिस्टम अलर्ट',
    'dash.tasks': 'आगामी कार्य',
    'dash.noTasks': 'कोई कार्य कतार में नहीं है',
    'dash.awaitingDirectives': 'नए निर्देशों की प्रतीक्षा है।',
    'dash.submitTask': 'कार्य सबमिट करें',
    'dash.missionObjective': 'मिशन का उद्देश्य...',
    'dash.planetaryResourceFlow': 'ग्रहीय संसाधन प्रवाह',
    'dash.multispectralTelemetry': 'मल्टीस्पेक्ट्रल टेलीमेट्री स्ट्रीम',
    'dash.solarIrradiance': 'सौर विकिरण सामान्य',
    'dash.soilEvap': 'मिट्टी का वाष्पीकरण सक्रिय',
    'dash.telemetryMissing': 'टेलीमेट्री गायब है',
    'dash.locating': 'सिस्टम खोजा जा रहा है...',

    // Landing
    'landing.aiTag': 'AI-संचालित कृषि',
    'landing.heroTitle1': 'सुरक्षा',
    'landing.heroTitle2': 'फसल',
    'landing.heroTitle3': 'जीवन',
    'landing.heroDesc': 'किसान साथी हमारे ग्रह की खाद्य प्रणालियों के लिए एक स्थायी भविष्य बनाने के लिए अत्याधुनिक पर्यावरणीय बुद्धिमत्ता और स्मार्ट खेती उपकरणों का लाभ उठाता है।',
    'landing.btnAnalyze': 'फसल विश्लेषण',
    'landing.btnMonitor': 'पर्यावरण निगरानी',
    'landing.stats1Label': 'फसलें संरक्षित',
    'landing.stats2Label': 'पानी की बचत',
    'landing.stats3Label': 'जोखिम सटीकता',
    'landing.stats4Label': 'किसान प्रभावित',
    'landing.launchModule': 'मॉड्यूल शुरू करें',
    'landing.futureTitle': 'खेती का भविष्य',
    'landing.futureDesc': 'आधुनिक पर्यावरणीय चुनौतियों के लिए डिज़ाइन किए गए बुद्धिमान उपकरण।',
    'landing.feature1Title': 'रोग पहचान AI',
    'landing.feature1Desc': 'फसल की तस्वीरें अपलोड करें और तत्काल निदान प्राप्त करें।',
    'landing.feature2Title': 'वास्तविक समय निगरानी',
    'landing.feature2Desc': 'बाढ़ क्षेत्र, तापमान वृद्धि और AQI निगरानी के लिए लाइव पर्यावरणीय अलर्ट।',
    'landing.feature3Title': 'स्मार्ट सिंचाई',
    'landing.feature3Desc': 'मिट्टी और मौसम के आधार पर पानी के उपयोग को अनुकूलित करें।',
    'landing.feature4Title': 'प्रत्यक्ष बाजार',
    'landing.feature4Desc': 'बिचौलियों को छोड़कर स्थानीय किसानों को उपभोक्ताओं से जोड़ें।',
    'landing.feature5Title': 'आपदा अलर्ट',
    'landing.feature5Desc': 'लू, तूफान और कीटों के लिए 72 घंटे आगे रहें।',
    'landing.ctaTitle': 'क्या आप अपनी फसलों को सुरक्षित करने के लिए तैयार हैं?',
    'landing.ctaDesc': '850,000+ किसानों और शोधकर्ताओं में शामिल हों।',
    'landing.launchBtn': 'किसान साथी शुरू करें',

    // Alerts
    'alert.heatwave': 'लू का अलर्ट',
    'alert.heatwaveMsg': 'अत्यधिक सौर प्रवाह का पता चला। सिंचाई प्रोटोकॉल डेल्टा निष्पादित करें।',
    'alert.winds': 'तेज रफ्तार हवाएं',
    'alert.windsMsg': 'हवा का वेग स्टेशन स्थिरता सीमा से अधिक है।',
    'alert.extremeHeat': 'अत्यधिक गर्मी सिंक',
    'alert.extremeHeatMsg': 'थर्मल रनवे का पता चला। आपातकालीन सिंचाई शुरू की जा रही है।',
    'alert.frost': 'पाला पड़ने वाला है',
    'alert.frostMsg': 'कम तापीय ऊर्जा। सुरक्षात्मक कैनोपी सक्रिय करें।',
    'alert.pathogen': 'रोगजनक जोखिम',
    'alert.pathogenMsg': 'अत्यधिक नमी का पता चला। कवक का जोखिम बढ़ गया है।',
    'alert.atmosphericCrisis': 'वायुमंडलीय संकट',
    'alert.atmosphericCrisisMsg': 'खतरनाक एरोसोल स्तर। संवेदनशील क्षेत्रों को सील करें।',
    'alert.systemNominal': 'सिस्टम सामान्य',
    'alert.systemNominalMsg': 'स्टेशन अल्फा कक्षीय उपग्रहों के साथ सिंक हो गया है।',

    // Marketplace
    'market.title': 'बाज़ार',
    'market.tag': 'नेटवर्क्ड सप्लाई',
    'market.desc': 'कृषि इनपुट और आउटपुट के लिए वाणिज्यिक केंद्र। नेटवर्क से सीधे बीज, उर्वरक और उपकरण प्राप्त करें।',
    'market.startListing': 'लिस्टिंग शुरू करें',
    'market.stats1Label': 'वैश्विक वस्तु सूचकांक',
    'market.stats2Label': 'सत्यापित किसान',
    'market.stats3Label': 'लेनदेन की मात्रा',
    'market.searchPlaceholder': 'संसाधन खोजें...',
    'market.initiateTrade': 'व्यापार शुरू करें',
    'market.cat.All': 'सभी',
    'market.cat.Crop': 'फसलें',
    'market.cat.Seed': 'बीज',
    'market.cat.Fertilizer': 'उर्वरक',
    'market.cat.Tool': 'उपकरण',
    'market.notFound': 'संसाधन नहीं मिले',
    'market.broadcasting': 'उपलब्ध नोड्स के लिए स्कैन ब्रॉडकास्ट किया जा रहा है...',
    'market.buyNow': 'अभी खरीदें',
    'market.processing': 'व्यापार संसाधित किया जा रहा है...',

    // Sell
    'sell.tag': 'विक्रेता कंसोल',
    'sell.title': 'कटाई सूची',
    'sell.desc': 'अपने कृषि उत्पादन और औद्योगिक आपूर्ति का प्रबंधन करें। वास्तविक समय में स्टॉक स्तर अपडेट करें।',
    'sell.newListing': 'नई लिस्टिंग',
    'sell.cancelEntry': 'प्रविष्टि रद्द करें',
    'sell.category': 'श्रेणी',
    'sell.price': 'कीमत',
    'sell.unit': 'इकाई',
    'sell.stock': 'उपलब्ध स्टॉक',
    'sell.missionParams': 'विवरण',
    'sell.deploy': 'लिस्टिंग तैनात करें',
    'sell.activeListings': 'सक्रिय लिस्टिंग',
    'sell.decommission': 'लिस्टिंग हटाएँ',
    'sell.zeroInventory': 'कोई स्टॉक नहीं मिला',
    'sell.initFirst': 'संचालन शुरू करने के लिए अपनी पहली लिस्टिंग जोड़ें।',
    'sell.accessRestricted': 'पहुंच प्रतिबंधित',
    'sell.identify': 'इन्वेंट्री कंसोल तक पहुँचने के लिए कृपया अपनी पहचान करें।',

    // Irrigation
    'irr.title': 'हाइड्रो जेनेसिस',
    'irr.tag': 'संसाधन अनुकूलन मैट्रिक्स',
    'irr.desc': 'ग्रहीय पैमाने के जलयोजन के लिए तंत्रिका वास्तुकला। उप-सतह मिट्टी टेलीमेट्री के साथ वास्तविक समय वायुमंडलीय विश्लेषण।',
    'irr.btnCompute': 'कंप्यूट शुरू करें',
    'irr.syncing': 'सिंक्रोनाइज़िंग',
    'irr.searchLabel': 'फसल कॉलोनी खोजें',
    'irr.searchPlaceholder': 'कोई भी फसल खोजें...',
    'irr.telemetryTitle': 'सेक्टर टेलीमेट्री',
    'irr.soilMoisture': 'मिट्टी की नमी',
    'irr.thermals': 'थर्मल्स (मिट्टी/वायु)',
    'irr.cloudDensity': 'बादल घनत्व',
    'irr.windVelocity': 'हवा का वेग',
    'irr.optimal': 'इष्टतम',
    'irr.manualOverride': 'मैनुअल ओवरराइड',
    'irr.standbyTitle': 'न्यूरल मैट्रिक्स स्टैंडबाय',
    'irr.standbyDesc': 'सिंचाई गणना शुरू करने के लिए टेलीमेट्री स्ट्रीम से एक फसल का चयन करें।',
    'irr.sustainability': 'स्थिरता सूचकांक',
    'irr.resourceEff': 'संसाधन दक्षता',
    'irr.globalYield': 'वैश्विक उपज प्रभाव',
    'irr.soilVitality': 'मिट्टी की जीवन शक्ति',
    'irr.inputValue': 'इनपुट मान',
    'irr.actionProtocol': 'एक्शन प्रोटोकॉल सत्यापित',
    'irr.litersPerPlant': 'लीटर / पौधा',
    'irr.temporalWindow': 'समय अंतराल',
    'irr.solarSync': 'सौर छाया समन्वय के लिए अनुकूलित।',
    'irr.cyclePulsation': 'चक्र स्पंदन',
    'irr.transpirationBuffering': 'गतिशील वाष्पोत्सर्जन बफरिंग सक्रिय।',
    'irr.consultingAI': 'AI से परामर्श किया जा रहा है...',
    'irr.bioDatabase': 'वैश्विक जैव-डेटाबेस खोजें:',

    // Crop Analysis
    'crop.title': 'फसल निदान AI',
    'crop.desc': 'रोगों का पता लगाने और तत्काल उपचार सिफारिशें प्राप्त करने के लिए अपनी फसल की एक फोटो अपलोड करें।',
    'crop.dropText': 'अपलोड करने के लिए छोड़ें',
    'crop.dragText': 'फोटो को यहाँ खींचें और छोड़ें',
    'crop.uploadGuidelines': 'मक्का, गेहूं, चावल, टमाटर, और अधिक के लिए काम करता है। 10MB तक JPEG/PNG।',
    'crop.selectImage': 'छवि चुनें',
    'crop.instantPhoto': 'तत्काल फोटो',
    'crop.scanningNeural': 'न्यूरल नेटवर्क स्कैन किया जा रहा है...',
    'crop.analyzeHealth': 'स्वास्थ्य विश्लेषण',
    'crop.diagnosisComplete': 'निदान पूरा हुआ',
    'crop.confidenceScore': 'आत्मविश्वास स्कोर',
    'crop.risk': 'जोखिम',
    'crop.treatmentProtocol': 'उपचार प्रोटोकॉल',
    'crop.immediateAction': 'तत्काल कार्रवाई',
    'crop.longTermPrevention': 'दीर्घकालिक रोकथाम',
    'crop.orderKit': 'रिकवरी किट ऑर्डर करें',
    'crop.standbyTitle': 'न्यूरल इंजन स्टैंडबाय',
    'crop.standbyDesc': 'स्कैन करने के बाद आपके विश्लेषण परिणाम यहां दिखाई देंगे। हमारा AI फसलों की 40+ प्रजातियों को संभालता है।',
    'crop.replacePhoto': 'फोटो बदलें',

    // Footer
    'footer.tagline': 'अगली पीढ़ी का पर्यावरणीय खुफिया मंच जो वैश्विक खाद्य स्थिरता और ग्रामीण समुदायों की रक्षा के लिए AI का लाभ उठाता है।',
    'footer.platform': 'प्लेटफार्म',
    'footer.resources': 'संसाधन',
    'footer.trust': 'ट्रस्ट',
    'footer.dashboard': 'विश्लेषण डैशबोर्ड',
    'footer.cropAI': 'फसल निदान AI',
    'footer.weather': 'मौसम जानकारी',
    'footer.handbook': 'किसान पुस्तिका',
    'footer.apiDoc': 'API दस्तावेज़',
    'footer.reports': 'स्थिरता रिपोर्ट',
    'footer.forum': 'सामुदायिक मंच',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'footer.security': 'सुरक्षा केंद्र',
    'footer.cookie': 'कुकी नीति',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    'footer.madeWith': 'निर्मित',

    // Admin
    'admin.desc': 'सिस्टम प्रशासन और ग्रहीय निरीक्षण।',
    'admin.genReport': 'सिस्टम रिपोर्ट जेनरेट करें',
    'admin.ebs': 'आपातकालीन प्रसारण प्रणाली',
    'admin.ebsDesc': 'सभी सक्रिय कर्मियों के डैशबोर्ड पर वास्तविक समय में अलर्ट भेजें।',
    'admin.alertType': 'अलर्ट प्रकार',
    'admin.headline': 'हेडलाइन',
    'admin.msgDetails': 'संदेश विवरण',
    'admin.commence': 'सिस्टम-व्यापी प्रसारण शुरू करें',
    'admin.userRegistry': 'उपयोगकर्ता रजिस्ट्री',
    'admin.cropReports': 'फसल रिपोर्ट',
    'admin.filterRecords': 'रिकॉर्ड फ़िल्टर करें...',
    'admin.allRegions': 'सभी क्षेत्र',
    'admin.entity': 'इकाई',
    'admin.status': 'स्थिति',
    'admin.type': 'प्रकार',
    'admin.actions': 'कार्रवाई',
    'admin.active': 'सक्रिय',
    'admin.cpuLoad': 'CPU लोड',
    'admin.storage': 'स्टोरेज',
    'admin.activeSessions': 'सक्रिय सत्र',
    'admin.alertRate': 'अलर्ट दर',

    // Profile
    'profile.title': 'प्रोफाइल सेटिंग्स',
    'profile.desc': 'अपनी खाता जानकारी और प्लेटफ़ॉर्म प्राथमिकताओं को अपडेट करें।',
    'profile.displayName': 'प्रदर्शित नाम',
    'profile.yourName': 'आपका नाम',
    'profile.platformRole': 'प्लेटफ़ॉर्म भूमिका',
    'profile.roleHint': 'भूमिकाएं मार्केटप्लेस (किसान) या GIS (विश्लेषक) जैसे विशिष्ट मॉड्यूल तक आपकी पहुंच निर्धारित करती हैं।',
    'profile.saveProfile': 'प्रोफाइल सहेजें',
    'profile.saving': 'परिवर्तन सहेजे जा रहे हैं...',
    'profile.signOut': 'साइन आउट',
    'profile.accountID': 'खाता ID',
    'profile.joined': 'शामिल हुए',
    'profile.back': 'वापस',
    'profile.unnamed': 'अनाम उपयोगकर्ता',
    'profile.account': 'खाता',

    // Auth labels
    'auth.tag': 'AI-संचालित ग्रहीय रक्षा प्रणाली',
    'auth.login': 'लॉगिन',
    'auth.register': 'पंजीकरण',
    'auth.loginDesc': 'अपने डैशबोर्ड और रिपोर्ट तक पहुंचें।',
    'auth.registerDesc': 'आज ही अपनी स्थिरता यात्रा शुरू करें।',
    'auth.iamFarmer': 'मैं एक किसान हूँ',
    'auth.iamConsumer': 'मैं एक उपभोक्ता हूँ',
    'auth.iamAnalyst': 'मैं एक विश्लेषक हूँ',
    'auth.googleAuth': 'गूगल के साथ जारी रखें',

    // Chat
    'chat.welcome': 'नमस्ते! मैं एग्रोएआई (AgroAI) हूँ, आपका ग्रहीय पर्यावरण सलाहकार। आज मैं आपके खेत की कैसे सहायता कर सकता हूँ?',
    'chat.placeholder': 'कुछ भी पूछें...',
    'chat.restore': 'इंटेलिजेंस सत्र बहाल करें',
    'chat.neuralLive': 'न्यूरल लाइव',
    'chat.error': 'न्यूरल इंजन से जुड़ते समय एक त्रुटि हुई।',
    'chat.noProcess': 'क्षमा करें, मैं उस अनुरोध को संसाधित नहीं कर सका।',

    // Auth
    'auth.welcomeBack': 'वापसी पर स्वागत है',
    'auth.join': 'किसान साथी से जुड़ें',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.name': 'पूरा नाम',
    'auth.signIn': 'साइन इन करें',
    'auth.createAccount': 'खाता बनाएं',
    'auth.or': 'या इसके साथ जारी रखें',

    // Admin
    'admin.title': 'कमांड कोर',
    'admin.users': 'सिस्टम उपयोगकर्ता',
    'admin.alerts': 'वैश्विक अलर्ट',
    'admin.placeholder': 'अलर्ट संदेश दर्ज करें...',

    // Feedback
    'feedback.title': 'सपोर्ट और फीडबैक',
    'feedback.btn': 'फीडबैक',
    'feedback.category': 'श्रेणी',
    'feedback.msg': 'आपका संदेश',
    'feedback.placeholder': 'अपनी समस्या का वर्णन करें या सुविधा का सुझाव दें...',
    'feedback.submit': 'फीडबैक भेजें',
    'feedback.success': 'धन्यवाद! आपका फीडबैक रिकॉर्ड कर लिया गया है।',
    'feedback.cat.bug': 'बग रिपोर्ट',
    'feedback.cat.feature': 'सुविधा अनुरोध',
    'feedback.cat.general': 'सामान्य फीडबैक',
  }
};

export const useLanguage = create<LanguageState>((set, get) => ({
  language: 'en',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => {
    const lang = get().language;
    return (translations[lang] as any)[key] || key;
  }
}));
