import { create } from 'zustand';

type Language = 'en' | 'hi';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar
    'nav.dashboard': 'Dashboard',
    'nav.crop': 'Crop Analysis',
    'nav.weather': 'Weather',
    'nav.irrigation': 'Irrigation',
    'nav.marketplace': 'Marketplace',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.getStarted': 'Get Started',
    'nav.signOut': 'Sign Out',
    'nav.switchLanguage': 'Switch to Hindi',
    'nav.appName': 'Kisan Sathi',
    
    // Generic
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error Occurred',
    'common.missingApiKey': 'Missing Weather API Key',
    'common.apiKeySetup': 'Please enter a valid OpenWeather API key in the settings panel to enable weather intelligence.',
    'common.organic': 'Organic',
    'common.sustainable': 'Sustainable',
    'common.verified': 'Verified',
    
    // Weather
    'weather.title': 'Weather Intelligence',
    'weather.search': 'Search city...',
    'weather.lastUpdated': 'Last Updated',
    'weather.feelsLike': 'Feels like',
    'weather.humidity': 'Humidity',
    'weather.wind': 'Wind Speed',
    'weather.visibility': 'Visibility',
    'weather.forecast': 'Extended Forecast',
    'weather.advisory': 'Heat Stress Advisory',
    'weather.opportunity': 'Irrigation Opportunity',
    
    // Dashboard
    'dash.title': 'Environmental Intel',
    'dash.systemsOptimal': 'Systems Optimal',
    'dash.refresh': 'Refresh Data',
    'dash.temp': 'Temperature',
    'dash.airQuality': 'Air Quality',
    'dash.precip': 'Precipitation',
    'dash.risk': 'Crop Risk Score',
    'dash.alerts': 'System Alerts',
    'dash.tasks': 'Upcoming Tasks',

    // Landing
    'landing.aiTag': 'AI-Powered Agriculture',
    'landing.heroTitle1': 'Protecting',
    'landing.heroTitle2': 'Crops',
    'landing.heroTitle3': 'Lives',
    'landing.heroDesc': 'Kisan Sathi leverages cutting-edge environmental intelligence and smart farming tools to build a sustainable future for our planet\'s food systems.',
    'landing.btnAnalyze': 'Analyze Crop',
    'landing.btnMonitor': 'Monitor Environment',
    'landing.futureTitle': 'The Future of Farming',
    'landing.futureDesc': 'Intelligent tools designed for modern environmental challenges.',
    'landing.feature1Title': 'Disease Detection AI',
    'landing.feature1Desc': 'Upload crop photos and get instant diagnosis with high precision confidence scoring.',
    'landing.feature2Title': 'Real-time Monitoring',
    'landing.feature2Desc': 'Live environmental alerts for flood zones, temperature spikes, and AQI monitoring.',
    'landing.feature3Title': 'Smart Irrigation',
    'landing.feature3Desc': 'Optimize water usage with AI-driven recommendations based on soil and weather data.',
    'landing.feature4Title': 'Direct Marketplace',
    'landing.feature4Desc': 'Connect local farmers with consumers bypassing intermediaries for fair trade.',
    'landing.feature5Title': 'Disaster Alerts',
    'landing.feature5Desc': 'Stay 72 hours ahead with predictive modeling for heatwaves, storms, and pests.',
    'landing.ctaTitle': 'Ready to secure your crops?',
    'landing.ctaDesc': 'Join 850,000+ farmers and researchers building a more resilient world.',
    'landing.launchBtn': 'Launch Kisan Sathi',

    // Marketplace
    'market.stats1Label': 'Global Commodity Index',
    'market.stats2Label': 'Verified Farmers',
    'market.stats3Label': 'Transaction Volume',
    'market.searchPlaceholder': 'Search planetary inventory...',
    'market.btnAddToCart': 'Add to Sphere',
    'market.btnDetails': 'Details',
    'market.bulkTitle': 'Large scale logistics required?',
    'market.bulkDesc': 'Our enterprise routing system manages cross-continental shipments for governments and research institutes.',
    'market.btnQuote': 'Request Quote',
    'market.cat.All': 'All',
    'market.cat.Produce': 'Produce',
    'market.cat.Technology': 'Technology',
    'market.cat.Seeds': 'Seeds',
    'market.cat.Tools': 'Tools',
    'market.cat.Fertilizers': 'Fertilizers',
    // Irrigation
    'irr.title': 'Hydro Genesis',
    'irr.tag': 'Resource Optimization Matrix',
    'irr.desc': 'Neural architecture for planetary scale hydration. Real-time atmospheric analysis synchronized with sub-surface soil telemetry.',
    'irr.btnCompute': 'Initialize Compute',
    'irr.syncing': 'Synchronizing',
    'irr.searchLabel': 'Search Crop Colony',
    'irr.searchPlaceholder': 'Search any crop...',
    'irr.telemetryTitle': 'Sector Telemetry',
    'irr.soilMoisture': 'Soil Moisture',
    'irr.thermals': 'Thermals (Soil/Air)',
    'irr.cloudDensity': 'Cloud Density',
    'irr.windVelocity': 'Wind Velocity',
    'irr.optimal': 'Optimal',
    'irr.manualOverride': 'Manual Override',
    'irr.standbyTitle': 'Neural Matrix Standby',
    'irr.standbyDesc': 'Select a biological colony from the telemetry stream to initialize irrigation vector calculations.',
    'irr.sustainability': 'Sustainability Index',
    'irr.resourceEff': 'Resource Efficiency',
    'irr.globalYield': 'Global Yield Impact',
    'irr.soilVitality': 'Soil Vitality',

    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.join': 'Join Kisan Sathi',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.signIn': 'Sign In',
    'auth.createAccount': 'Create Account',
    'auth.googleAuth': 'Google Authentication',
    'auth.tag': 'Secure the future of your environment.',
    'auth.or': 'Or continue with',

    // Admin
    'admin.title': 'Command Core',
    'admin.users': 'System Users',
    'admin.alerts': 'Global Alerts',
    'admin.placeholder': 'Enter alert message...',
    
    // Feedback
    'feedback.title': 'Support & Feedback',
    'feedback.btn': 'Feedback',
    'feedback.category': 'Category',
    'feedback.msg': 'Your Message',
    'feedback.placeholder': 'Describe your issue or suggest a feature...',
    'feedback.submit': 'Send Feedback',
    'feedback.success': 'Thank you! Your feedback has been recorded.',
    'feedback.cat.bug': 'Bug Report',
    'feedback.cat.feature': 'Feature Request',
    'feedback.cat.general': 'General Feedback',
  },
  hi: {
    // Navbar
    'nav.dashboard': 'डैशबोर्ड',
    'nav.crop': 'फसल विश्लेषण',
    'nav.weather': 'मौसम',
    'nav.irrigation': 'सिंचाई',
    'nav.marketplace': 'मार्केटपलेस',
    'nav.admin': 'प्रशासक',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.getStarted': 'शुरू करें',
    'nav.signOut': 'साइन आउट',
    'nav.switchLanguage': 'English में बदलें',
    'nav.appName': 'किसान साथी',

    // Generic
    'common.search': 'खोजें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि हुई',
    'common.missingApiKey': 'मौसम एपीआई कुंजी गायब है',
    'common.apiKeySetup': 'मौसम जानकारी सक्षम करने के लिए कृपया सेटिंग्स पैनल में एक वैध ओपनवेदर एपीआई कुंजी दर्ज करें।',
    'common.organic': 'जैविक',
    'common.sustainable': 'सतत',
    'common.verified': 'सत्यापित',
    
    // Weather
    'weather.title': 'मौसम जानकारी',
    'weather.search': 'शहर खोजें...',
    'weather.lastUpdated': 'पिछली बार अपडेट किया गया',
    'weather.feelsLike': 'जैसा महसूस होता है',
    'weather.humidity': 'नमी',
    'weather.wind': 'हवा की गति',
    'weather.visibility': 'दृश्यता',
    'weather.forecast': 'पूर्वानुमान',
    'weather.advisory': 'गर्मी के तनाव की सलाह',
    'weather.opportunity': 'सिंचाई का अवसर',
    
    // Dashboard
    'dash.title': 'पर्यावरण इंटेलिजेंस',
    'dash.systemsOptimal': 'सिस्टम ठीक है',
    'dash.refresh': 'डेटा रीफ्रेश करें',
    'dash.temp': 'तापमान',
    'dash.airQuality': 'वायु गुणवत्ता',
    'dash.precip': 'वर्षा',
    'dash.risk': 'फसल जोखिम स्कोर',
    'dash.alerts': 'सिस्टम अलर्ट',
    'dash.tasks': 'आगामी कार्य',

    // Landing
    'landing.aiTag': 'AI-संचालित कृषि',
    'landing.heroTitle1': 'सुरक्षा',
    'landing.heroTitle2': 'फसल',
    'landing.heroTitle3': 'जीवन',
    'landing.heroDesc': 'किसान साथी हमारे ग्रह की खाद्य प्रणालियों के लिए एक स्थायी भविष्य बनाने के लिए अत्याधुनिक पर्यावरणीय बुद्धिमत्ता और स्मार्ट खेती उपकरणों का लाभ उठाता है।',
    'landing.btnAnalyze': 'फसल विश्लेषण',
    'landing.btnMonitor': 'पर्यावरण निगरानी',
    'landing.futureTitle': 'खेती का भविष्य',
    'landing.futureDesc': 'आधुनिक पर्यावरणीय चुनौतियों के लिए डिज़ाइन किए गए बुद्धिमान उपकरण।',
    'landing.feature1Title': 'रोग पहचान AI',
    'landing.feature1Desc': 'फसल की तस्वीरें अपलोड करें और तत्काल निदान प्राप्त करें।',
    'landing.feature2Title': 'वास्तविक समय निगरानी',
    'landing.feature2Desc': 'बाढ़ क्षेत्र, तापमान वृद्धि और AQI निगरानी के लिए लाइव पर्यावरणीय अलर्ट।',
    'landing.feature3Title': 'स्मार्ट सिंचाई',
    'landing.feature3Desc': 'मिट्टी और मौसम के आधार पर पानी के उपयोग को अनुकूलित करें।',
    'landing.feature4Title': 'प्रत्यक्ष बाजार',
    'landing.feature4Desc': 'बिचौलियों को छोड़कर स्थानीय किसानों को उपभोक्ताओं से जोड़ें।',
    'landing.feature5Title': 'आपदा अलर्ट',
    'landing.feature5Desc': 'लू, तूफान और कीटों के लिए 72 घंटे आगे रहें।',
    'landing.ctaTitle': 'क्या आप अपनी फसलों को सुरक्षित करने के लिए तैयार हैं?',
    'landing.ctaDesc': '850,000+ किसानों और शोधकर्ताओं में शामिल हों।',
    'landing.launchBtn': 'किसान साथी शुरू करें',

    // Marketplace
    'market.stats1Label': 'वैश्विक वस्तु सूचकांक',
    'market.stats2Label': 'सत्यापित किसान',
    'market.stats3Label': 'लेनदेन की मात्रा',
    'market.searchPlaceholder': 'ग्रह सूची खोजें...',
    'market.btnAddToCart': 'खरीदें',
    'market.btnDetails': 'विवरण',
    'market.bulkTitle': 'बड़े पैमाने पर रसद की आवश्यकता है?',
    'market.bulkDesc': 'हमारी उद्यम रूटिंग प्रणाली सरकारों और संस्थानों के लिए शिपमेंट का प्रबंधन करती है।',
    'market.btnQuote': 'उद्धरण मांगें',
    'market.cat.All': 'सभी',
    'market.cat.Produce': 'उत्पाद',
    'market.cat.Technology': 'तकनीक',
    'market.cat.Seeds': 'बीज',
    'market.cat.Tools': 'उपकरण',
    'market.cat.Fertilizers': 'उर्वरक',

    // Irrigation
    'irr.title': 'हाइड्रो जेनेसिस',
    'irr.tag': 'संसाधन अनुकूलन मैट्रिक्स',
    'irr.desc': 'ग्रहीय पैमाने के जलयोजन के लिए तंत्रिका वास्तुकला। उप-सतह मिट्टी टेलीमेट्री के साथ वास्तविक समय वायुमंडलीय विश्लेषण।',
    'irr.btnCompute': 'कंप्यूट शुरू करें',
    'irr.syncing': 'सिंक्रोनाइज़िंग',
    'irr.searchLabel': 'फसल कॉलोनी खोजें',
    'irr.searchPlaceholder': 'कोई भी फसल खोजें...',
    'irr.telemetryTitle': 'सेक्टर टेलीमेट्री',
    'irr.soilMoisture': 'मिट्टी की नमी',
    'irr.thermals': 'थर्मल्स (मिट्टी/वायु)',
    'irr.cloudDensity': 'बादल घनत्व',
    'irr.windVelocity': 'हवा का वेग',
    'irr.optimal': 'इष्टतम',
    'irr.manualOverride': 'मैनुअल ओवरराइड',
    'irr.standbyTitle': 'न्यूरल मैट्रिक्स स्टैंडबाय',
    'irr.standbyDesc': 'सिंचाई गणना शुरू करने के लिए टेलीमेट्री स्ट्रीम से एक फसल का चयन करें।',
    'irr.sustainability': 'स्थिरता सूचकांक',
    'irr.resourceEff': 'संसाधन दक्षता',
    'irr.globalYield': 'वैश्विक उपज प्रभाव',
    'irr.soilVitality': 'मिट्टी की जीवन शक्ति',

    // Auth
    'auth.welcomeBack': 'वापसी पर स्वागत है',
    'auth.join': 'किसान साथी से जुड़ें',
    'auth.login': 'लॉगिन',
    'auth.register': 'पंजीकरण',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.name': 'पूरा नाम',
    'auth.signIn': 'साइन इन करें',
    'auth.createAccount': 'खाता बनाएं',
    'auth.googleAuth': 'गूगल प्रमाणीकरण',
    'auth.tag': 'अपने पर्यावरण का भविष्य सुरक्षित करें।',
    'auth.or': 'या इसके साथ जारी रखें',

    // Admin
    'admin.title': 'कमांड कोर',
    'admin.users': 'सिस्टम उपयोगकर्ता',
    'admin.alerts': 'वैश्विक अलर्ट',
    'admin.placeholder': 'अलर्ट संदेश दर्ज करें...',

    // Feedback
    'feedback.title': 'सपोर्ट और फीडबैक',
    'feedback.btn': 'फीडबैक',
    'feedback.category': 'श्रेणी',
    'feedback.msg': 'आपका संदेश',
    'feedback.placeholder': 'अपनी समस्या का वर्णन करें या सुविधा का सुझाव दें...',
    'feedback.submit': 'फीडबैक भेजें',
    'feedback.success': 'धन्यवाद! आपका फीडबैक रिकॉर्ड कर लिया गया है।',
    'feedback.cat.bug': 'बग रिपोर्ट',
    'feedback.cat.feature': 'सुविधा अनुरोध',
    'feedback.cat.general': 'सामान्य फीडबैक',
  }
};

export const useLanguage = create<LanguageState>((set, get) => ({
  language: 'en',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => {
    const lang = get().language;
    return (translations[lang] as any)[key] || key;
  }
}));
